name: 11-gha-build -repo-secret
on: 
  workflow_dispatch:

env:
  DB_U: dbuser1
  DB_P: ${{ secrets.DB.PASSWORD}}

jobs:
  show-code-secret:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: display env username
        run: echo "u=${{ env.DB_U}}"
      - name: display env password
        run: echo "p=${{ env.DB_P }}"   
