name: 13-gha-build -repo-variable
on: 
  workflow_dispatch:

env:
  DB_U: ${{ vars.DB_USERNAME }}
  DB_P: ${{ secrets.DB_PASSWORD }}

jobs:
  show-code-secret:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: display env username
        run: echo "u=${{ env.DB_U}}"
      - name: display env password
        run: echo "p=${{ env.DB_P }}" 
      - name: 0429 with python
        run: python secrets.py 

