name: 14-gha-build -env-variable
on: 
  workflow_dispatch:



jobs:
  show-dev-env-variable:
    environment: DEV
    env:
      DB_U: ${{ vars.DB_USER }}
      DB_P: ${{ secrets.DB_KEY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: display env username
        run: echo "u=${{ env.DB_U}}"
      - name: display env password
        run: echo "p=${{ env.DB_P }}" 

  show-prod-env-variable:
    environment: DEV
    env:
      DB_U: ${{ vars.DB_USER }}
      DB_P: ${{ secrets.DB_KEY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: display env username
        run: echo "u=${{ env.DB_U}}"
      - name: display env password
        run: echo "p=${{ env.DB_P }}"         


