name: 2-gha-build-artifact
on: workflow_dispatch

jobs:
  build-on-windows:
    runs-on: windows-2022
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: pyinstaller install
        run: pip install pyinstaller
      - name: build generation
        run: pyinstaller sha256.py -F
      - name: upload sha256.exe
        uses: actions/upload-artifact@v4
        with:
          name: sha256-win-exe
          path: dist/sha256.exe  
