name: 2-gha-build-artifact
on: workflow_dispatch

jobs:
  build-on-windows:
    runs-on: windows-2022
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: pyinstaller install
        run: pip install pyinstaller
      - name: build generation
        run: pyinstaller sha256.py -F
      - name: upload sha256.exe
        uses: actions/upload-artifact@v4
        with:
          name: sha256-win-exe
          path: dist/sha256.exe
          
  build-on-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: pyinstaller install
        run: pip install pyinstaller
      - name: build generation
        run: pyinstaller sha256.py -F
      - name: upload binary file
        uses: actions/upload-artifact@v4
        with:
          name: sha256-linux
          path: dist/sha256
          
  build-on-mac:
    runs-on: macos-12
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: pyinstall install
        run:  pip3 install pyinstaller
      - name: build binary
        run: pyinstaller sha256.py -F
      - name: upload binary file
        uses: action/upload-artifact@v4
        with:
          name: sha256-mac
          path: dist/sha256              
