name: 4-gha-build-artifact -download
on: workflow_dispatch

jobs:
  build-on-windows:
    runs-on: windows-2022
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: pyinstaller install
        run: pip install pyinstaller
      - name: build generation
        run: pyinstaller sha256.py -F
      - name: upload sha256.exe
        uses: actions/upload-artifact@v4
        with:
          name: sha256-win-exe
          path: dist/sha256.exe

  download-build-on-windows:
    runs-on: windows-2022
    needs: build-on-windows
    steps:
      - name: download sha256.exe
        uses: actions/download-artifact@v4
        with:
          name: sha256-win-exe
          path: sha256.exe
      - name: validate sha256.exe file
        run: |
          ls
          ./sha256.exe sha256.exe