name: 8-gha-build -env - python-app
on: workflow_dispatch

jobs:
  show-linux-env:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: check default env
        run: env
      - name: print env
        run: echo $GITHUB_REPOSITORY
      - name:
        run: python env.py            